#!/bin/bash
### BEGIN INIT INFO
# Provides:          feuerwand
# Required-Start:    $local_fs $network $named $time $syslog
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       Iptables service script
### END INIT INFO

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

START_SCRIPT=$DIR/src/start.sh
STOP_SCRIPT=$DIR/src/stop.sh
RUNAS=root

PIDFILE=/var/run/feuerwand.pid
LOGFILE=/var/log/feuerwand.log

start() {
  if [ -f /var/run/$PIDNAME ] && kill -0 $(cat /var/run/$PIDNAME); then
    echo 'Service already running' >&2
    return 1
  fi
  echo 'Starting service ...' >&2
  local CMD="$START_SCRIPT &>> \"$LOGFILE\" & echo \$!"
  su -c "$CMD" $RUNAS > "$PIDFILE"
  echo 'Service started' >&2
}

stop() {
  echo 'Stopping service ...' >&2
  # kill -15 $(cat "$PIDFILE") && rm -f "$PIDFILE"
  local CMD="$STOP_SCRIPT &>> \"$LOGFILE\" & echo \$!"
  su -c "$CMD" $RUNAS > /dev/null
  echo 'Service stopped' >&2
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  retart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
esac
